services:
  backend:
    build:
      context: ./backend
    container_name: school_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://neondb_owner:npg_IKecRfm4o6gZ@ep-aged-silence-azt04b35-pooler.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=supersecretkey_for_dev_only
      - GOOGLE_SHEET_WEBHOOK_URL=https://script.google.com/macros/s/AKfycbxGfcWXmnD0-pKDZiC8NbOQn0v_9fsfIw18iaFgv0PpUE8Pt0myFUGVNhswWnxXmNQ49A/exec

  frontend:
    build:
      context: ./frontend
    container_name: school_frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend


